### ISSUE TITLE
Параметры подключения внутри скрипта

### ISSUE THREAD

**Issue by SimonOsipov** [petrovao87/test_api#1]
https://github.com/petrovao87/test_api/blob/1e4cdd9241249d82622491de8f9fcf2467ef7426/db.py#L7

Хороший тон - вынести это в отдельный файл и чтобы пользователь редактировал только его, а не лез в код.

**Comment by petrovao87** [comment]
https://github.com/petrovao87/test_api/commit/6418cd2ff0b994c6c63c5452d657276dc41aee5c
