### ISSUE TITLE
Потенциал потерять все данные

### ISSUE THREAD

**Issue by SimonOsipov** [petrovao87/test_api#3]
https://github.com/petrovao87/test_api/blob/1e4cdd9241249d82622491de8f9fcf2467ef7426/db.py#L90

Представь себе, что я решил создать все таблички уже в существующей бд и схеме, вот эта строка дропнет мне все данные и создаст новые таблицы. Я потеряю свои данные)

https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=drop_all#sqlalchemy.schema.MetaData.drop_all

**Comment by petrovao87** [comment]
https://github.com/petrovao87/test_api/commit/094f182ec456cdba571dfced7a6bf017c3a62654
