### ISSUE TITLE
Номер ошибки неверный

### ISSUE THREAD

**Issue by SimonOsipov** [petrovao87/test_api#4]
https://github.com/petrovao87/test_api/blob/1e4cdd9241249d82622491de8f9fcf2467ef7426/api.py#L80

404 это про страницы)
204 No content сюда подходит лучше

**Comment by petrovao87** [comment]
https://github.com/petrovao87/test_api/commit/4d9f21e0d41cd1c7a6fd8778b27a1008518ea72c
