### ISSUE TITLE
А чем они отличаются?

### ISSUE THREAD

**Issue by SimonOsipov** [petrovao87/test_api#7]
https://github.com/petrovao87/test_api/blob/1e4cdd9241249d82622491de8f9fcf2467ef7426/api.py#L270-L282

**Comment by petrovao87** [comment]
https://github.com/petrovao87/test_api/commit/7048f05a2feb7c60b3dac5c9ca0cb3920201f6ef

Ну в первом случае если у владельца есть еще процессы, то мы его не удаляем, если у него только один процесс, то мы его удаляем вместе с ним.
