### ISSUE TITLE
Общие комментарии

### ISSUE THREAD

**Issue by SimonOsipov** [petrovao87/test_api#8]
1) История коммитов - это хорошо. Что не сразу `initial commit`. Но вот что ты пишешь в заголовке - это прям очень не очень. Прочитав заголовок коммита, я должен понять, что там происходит при внедрении этого коммита.
2) Виртуальное окружение. Раз пишешь, что надо установить зависимости, значит надо написать, что нужно виртуальное окружение. Правило хорошего тона.
3) раздел for example в README хороший, но вот только нужно показать реальные данные, а не названия `'activity_flag': 'activity_flag',`

**Comment by petrovao87** [comment]
https://github.com/petrovao87/test_api/commit/a60a4de3e1d4b120815004d26853ab19f0d255d6
